### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/enterprise-extensions#114]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] account_accountant_ux
- [ ] account_journal_book_report
- [ ] helpdesk_project_ux
- [ ] helpdesk_solutions
- [ ] helpdesk_ux
- [ ] hr_timesheet_ux
- [ ] l10n_ar_currency_update
- [ ] l10n_ar_website_sale_coupon
- [ ] mis_builder_cash_flow
- [ ] project_forecast_ux
- [ ] purchase_subscription
- [ ] sale_subscription_ux
- [ ] transindar_personalization
- [ ] website_quote_public
- [ ] website_quote_ux
