### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/enterprise-extensions#25]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_journal_book_report
- [ ] account_usability
- [ ] adhoc_modules_server
- [ ] crm_voip_usability
- [ ] infrastructure_contract
- [ ] portal_sale_distributor
- [ ] purchase_contract
- [ ] sale_contract_lines_sequence
- [ ] sale_contract_prices_update
- [ ] sale_contract_usability
- [ ] support_branding
- [ ] transindar_personalization
- [ ] web_support_server
- [ ] web_support_server_issue
- [ ] website_infrastructure_contract
- [ ] website_quote_public
- [ ] website_quote_usability
